mosquitto:
  image: toke/mosquitto:latest
  ports:
    - "1883:1883"
    - "9001:9001"
  volumes:
    - ./mosquitto/config:/mqtt/config:ro
    - ./mosquitto/log:/mqtt/log
    - ./mosquitto/data/:/mqtt/data/

mqtt2logstash:
  build: mqtt2logstash
  command: app "mosquitto:1883" "docker-log/#" "logstash:5000"
  links:
    - mosquitto
